version: 0.2
phases:
  pre_build:
    commands:
      - echo "pre build things can mention"
  build:
    commands:
      - echo "build phase"
      - mvn clean package
  post_build:
    commands:
      - echo "post deployment"
artifacts:
  files:
    - ./targe/**/*